### ISSUE TITLE
Delay overlay opacity

### ISSUE THREAD

**Issue by asfernandes** [Availity/react-block-ui#17]
Sorry, this is not a library bug, but I'm trying to delay the opacity change as a transition but anything I tried didn't work.

Something as:

```css
.block-ui-overlay {
	transition-property: opacity;
	transition-delay: 3s;
}
```

I'm not expert on CSS transition. Can this be made?

**Comment by TheSharpieOne** [comment]
Sorry I missed this issue. You cannot use transitions as when the element appears it is added to the DOM and transitions don't apply. It's considered it's initial state and not a transition.
You can use CSS animations. See: https://stackblitz.com/edit/react-block-ui-1x-umskff?file=style.css

```css
.block-ui-overlay {
  animation: 1s fadein .5s both;
  /* wait 1s, fadein over .5s, apply the animation styles both before and after. */
}


@keyframes fadein {
    from { opacity: 0; }
    to   { opacity: .5; }
}
```
