### ISSUE TITLE
How to change the overlay opacity.

### ISSUE THREAD

**Issue by prince272** [Availity/react-block-ui#58]

**Comment by chrishavekost** [comment]
The overlay opacity is [defined here](https://github.com/Availity/react-block-ui/blob/master/src/style.css#L32). A simple way to override the value would be to add something like

```css
.block-ui-overlay {
  opacity: 0.8; // override default of 0.5 to make message more visible
}
```
to your custom .css or .scss file
